{
  homebrew = {
    taps = [
      "acsandmann/tap"
      "barutsrb/tap"
      "gcenx/wine"
      "jnsahaj/lumen"
      "nahive/spotify-notify"
      "nikitabobko/tap"
      "oven-sh/bun"
    ];

    brews = [
      "assimp"
      "bat"
      "btop"
      "chafa"
      "cloudflared"
      "cmake"
      "cocoapods"
      "coreutils"
      "couchdb"
      "deno"
      "dipc"
      "fastfetch"
      "fd"
      "ffmpeg"
      "fish"
      "fzf"
      "gh"
      "git"
      "git-filter-repo"
      "go"
      "imagemagick"
      "lazydocker"
      "lazygit"
      "libcaca"
      "libpq"
      "lua"
      "mas"
      "mosh"
      "neovim"
      "ninja"
      "node@24"
      "opencode"
      "poppler"
      "pyenv"
      "raylib"
      "rclone"
      "repomix"
      "stow"
      "swiftformat"
      "swiftlint"
      "terminal-notifier"
      "tmux"
      "tree-sitter-cli"
      "tree-sitter@0.25"
      "uv"
      "watchman"
      "wget"
      "xcbeautify"
      "xcodegen"
      "yazi"
      "zoxide"
      # tap-qualified formulae
      "acsandmann/tap/rift"
      "oven-sh/bun/bun"
      # Intentionally dropped (rustup already provides these):
      #   "rust"
    ];

    casks = [
      "1password-cli"
      "aerospace"
      "alcove"
      "appcleaner"
      "audacity"
      "balenaetcher"
      "betterdisplay"
      "brave-browser@nightly"
      "claude"
      "clop"
      "db-browser-for-sqlite"
      "displaperture"
      "docker-desktop"
      "epic-games"
      "equibop"
      "figma"
      "firefox"
      "ghostty"
      "github"
      "google-drive"
      "gstreamer-runtime"
      "httpie-desktop"
      "hyperkey"
      "jordanbaird-ice"
      "karabiner-elements"
      "linearmouse"
      "logi-options+"
      "macs-fan-control"
      "music-presence"
      "ngrok"
      "nordvpn"
      "obs"
      "obsidian"
      "opencode-desktop"
      "orbstack"
      "prismlauncher"
      "qmk-toolbox"
      "raycast"
      "spotify-notify"
      "stats"
      "steam"
      "thaw"
      "the-unarchiver"
      "utm"
      "vesktop"
      "vlc"
      "warp"
      "wine-crossover"
      "zen"
      "zerotier-one"
      "zulu@17"
    ];

    # masApps populated in a follow-up after `mas list` returns real IDs
    # (Spotlight reindex was triggered in Phase 0 — see ~/.config/nix.bak/PENDING-mas-ids.md).
    masApps = { };
  };
}
