#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
	active_color=0xff000000
	inactive_color=0xff131313
	background_color=0x302c2e34
	blur_radius=25
)

borders "${options[@]}"
# active_color=0xffd3d3d3
# inactive_color=0xffd9d9d9
