[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.ghostty]
input_path = '~/.config/matugen/templates/config'
output_path = '~/.config/ghostty/themes/colors'

[templates.neovim]
input_path = '~/.config/matugen/templates/neovim.template'
output_path = '~/.config/nvim/lua/colors/matugen.lua'

[templates.legcord] # legcord (old armcord) client
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/Library/Application\ Support/legcord/quickCss.css' # for flatpak installation
