[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.ghostty]
input_path = '~/.config/matugen/templates/config'
output_path = '~/.config/ghostty/themes/colors'

[templates.neovim]
input_path = '~/.config/matugen/templates/neovim.template'
output_path = '~/.config/nvim/lua/colors/matugen.lua'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spotify-colors.ini'
output_path = '~/.config/spicetify/Themes/Comfy/color.ini'

[templates.legcord] # legcord (old armcord) client
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/Library/Application Support/legcord/quickCss.css' # for flatpak installation

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux-colors.conf'
output_path = '~/.config/tmux/colors.conf'

[config.custom_colors]
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
orange = "#fab387"
purple = "#cba6f7"
