#!/bin/bash

# yabai -m config menubar_opacity 0.0

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off

# padding set to 12px
yabai -m config top_padding 16
yabai -m config bottom_padding 16
yabai -m config left_padding 16
yabai -m config right_padding 16
yabai -m config window_gap 16
yabai -m config external_bar all:40:0
yabai -m config window_shadow off
yabai -m config focus_follows_mouse autofocus

yabai -m config window_border off
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xff7aa2f7 # Tokyonight blue
yabai -m config normal_window_border_color 0xfff7768e # Tokyonight red

# -- mouse settings --

# center mouse on window with focus
# yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# Split ratio
# yabai -m config auto_balance on
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"

# Setup spaces
function setup_space {
	local idx="$1"
	local name="$2"
	local space=
	echo "setup space $idx : $name"

	space=$(yabai -m query --spaces --space "$idx")
	if [ -z "$space" ]; then
		yabai -m space --create
	fi

	yabai -m space "$idx" --label "$name"
	echo yabai -m space "$idx" --label "$name"
}

setup_space 1 Web
setup_space 2 Code
setup_space 3 Todo
setup_space 4 Music
setup_space 5 Design
setup_space 6 School
setup_space 7 Social

# Assign apps to specific spaces
yabai -m rule --add app="^(Arc|Discord)$" space=^1
yabai -m rule --add app="^(VSCode|Alacritty|Zed)$" space=^2
yabai -m rule --add app="^(Notion|Superlist)$" space=^3
yabai -m rule --add app="^(Spotify|YouTube Music Desktop App)$" space=^4
yabai -m rule --add app="^(Figma|After Effects|Lightroom|Photoshop)$" space=^5
yabai -m rule --add app="^(Keynote|Microsoft PowerPoint|Microsoft Word)$" space=^6
yabai -m rule --add app="^(Discord|Messages)$" space=^7

# Manage apps and windows
yabai -m rule --add app="^(Messages|LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Alfred|Activity Monitor|Clock|Karabiner-Elements|Plexamp|Alfred Preferences|ImageOptim|The Unarchiver|Transmission|Installer|Hosting AU|Numi|IINA)$" manage=off
yabai -m rule --add label="Small windows" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="GLMv4" app="^GLMv4$" title="(Preparations for Measurements)" manage=off
yabai -m rule --add label="Cyberduck" app="^Cyberduck$" title="(Transfers)" manage=off
yabai -m rule --add label="Mail New Message" app="^Mail$" title="(New Message)" manage=off
yabai -m rule --add label="Steam Helper" app="^Steam Helper$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Activity Windows" title="^Activity$" manage=off
yabai -m rule --add app="^Adobe (After Effects|Audition|Media Encoder|Lightroom)$" role="AXLayoutArea" subrole="AXFloatingWindow" manage=on
yabai -m rule --add app="^IINA$" sticky=on layer=above manage=off

echo "Yabai configuration loaded…"
