# Input configuration

input {
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0

    repeat_rate = 40
    repeat_delay = 600
    numlock_by_default = true

    touchpad {
        natural_scroll = true
        clickfinger_behavior = true
    }
}

# Three-finger horizontal swipe to switch workspaces
gesture = 3, horizontal, workspace
