# Look and feel — gaps, borders, decorations, animations

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 8
    rounding_power = 2

    screen_shader = ~/.config/hypr/shaders/vibrance.glsl

    active_opacity = 0.95
    inactive_opacity = 0.9

    shadow {
        enabled = true
        range = 8
        render_power = 3
    }

    blur {
        enabled = true
        size = 8
        passes = 3
        vibrancy = 0.1696
    }
}

animations {
    enabled = yes, please :)

    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    animation = global,        1, 10,   default
    animation = border,        1, 5.39, easeOutQuint
    animation = windows,       1, 4.79, easeOutQuint
    animation = windowsIn,     1, 4.1,  easeOutQuint, popin 87%
    animation = windowsOut,    1, 1.49, linear,       popin 87%
    animation = fadeIn,        1, 1.73, almostLinear
    animation = fadeOut,       1, 1.46, almostLinear
    animation = fade,          1, 3.03, quick
    animation = layers,        1, 3.81, easeOutQuint
    animation = layersIn,      1, 4,    easeOutQuint, fade
    animation = layersOut,     1, 1.5,  linear,       fade
    animation = fadeLayersIn,  1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces,    1, 1.94, almostLinear, fade
    animation = workspacesIn,  1, 1.21, almostLinear, fade
    animation = workspacesOut, 1, 1.94, almostLinear, fade
    animation = zoomFactor,    1, 7,    quick
}

dwindle {
    pseudotile = true
    preserve_split = true
    force_split = 2
}

master {
    new_status = master
}

cursor {
    hide_on_key_press = true
}

binds {
    hide_special_on_workspace_change = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
    force_default_wallpaper = 0
    vfr = false
    key_press_enables_dpms = true
    mouse_move_enables_dpms = true
}

render {
    direct_scanout = false
}
