require("various-textobjs").setup({
  forwardLooking = {
    small = 5,
    big = 15,
  },
  keymaps = {
    useDefaults = true,
    disabled = { "gc" }, -- disable comment textobj, we use ts-comments
  },
})

-- Additional custom keymaps for better text objects
local wk = require("which-key")
wk.add({
  { "a", mode = { "o", "x" }, group = "around" },
  { "i", mode = { "o", "x" }, group = "inside" },
  { "ii", mode = { "o", "x" }, desc = "inside indent" },
  { "ai", mode = { "o", "x" }, desc = "around indent" },
  { "iS", mode = { "o", "x" }, desc = "inside subword" },
  { "aS", mode = { "o", "x" }, desc = "around subword" },
  { "ik", mode = { "o", "x" }, desc = "inside key" },
  { "ak", mode = { "o", "x" }, desc = "around key" },
  { "iv", mode = { "o", "x" }, desc = "inside value" },
  { "av", mode = { "o", "x" }, desc = "around value" },
  { "in", mode = { "o", "x" }, desc = "inside number" },
  { "an", mode = { "o", "x" }, desc = "around number" },
  { "ir", mode = { "o", "x" }, desc = "inside restOfIndent" },
  { "ar", mode = { "o", "x" }, desc = "around restOfIndent" },
  { "iU", mode = { "o", "x" }, desc = "inside URL" },
  { "aU", mode = { "o", "x" }, desc = "around URL" },
  { "ig", mode = { "o", "x" }, desc = "inside diagnostic" },
  { "ag", mode = { "o", "x" }, desc = "around diagnostic" },
  { "iz", mode = { "o", "x" }, desc = "inside fold" },
  { "az", mode = { "o", "x" }, desc = "around fold" },
  { "im", mode = { "o", "x" }, desc = "inside chainMember" },
  { "am", mode = { "o", "x" }, desc = "around chainMember" },
  { "iC", mode = { "o", "x" }, desc = "inside cssSelector" },
  { "aC", mode = { "o", "x" }, desc = "around cssSelector" },
  { "iH", mode = { "o", "x" }, desc = "inside htmlAttribute" },
  { "aH", mode = { "o", "x" }, desc = "around htmlAttribute" },
  { "ie", mode = { "o", "x" }, desc = "inside nearEoL" },
  { "ae", mode = { "o", "x" }, desc = "around nearEoL" },
  { "iL", mode = { "o", "x" }, desc = "inside lineCharacterwise" },
  { "aL", mode = { "o", "x" }, desc = "around lineCharacterwise" },
  { "iM", mode = { "o", "x" }, desc = "inside mdlink" },
  { "aM", mode = { "o", "x" }, desc = "around mdlink" },
  { "iE", mode = { "o", "x" }, desc = "inside mdEmphasis" },
  { "aE", mode = { "o", "x" }, desc = "around mdEmphasis" },
  { "iD", mode = { "o", "x" }, desc = "inside mdFencedCodeBlock" },
  { "aD", mode = { "o", "x" }, desc = "around mdFencedCodeBlock" },
  { "io", mode = { "o", "x" }, desc = "inside toNextClosingBracket" },
  { "ao", mode = { "o", "x" }, desc = "around toNextClosingBracket" },
  { "iq", mode = { "o", "x" }, desc = "inside toNextQuotationMark" },
  { "aq", mode = { "o", "x" }, desc = "around toNextQuotationMark" },
  { "iQ", mode = { "o", "x" }, desc = "inside anyQuote" },
  { "aQ", mode = { "o", "x" }, desc = "around anyQuote" },
  { "iB", mode = { "o", "x" }, desc = "inside anyBracket" },
  { "aB", mode = { "o", "x" }, desc = "around anyBracket" },
})