-- Catppuccin - Generated by FormalConf
-- Neovim colorscheme configuration for LazyVim

return {
  {
    "catppuccin/nvim",
    name = "formalconf-colorscheme",
    priority = 1000,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin-mocha",
    },
  },

  {
    "f-person/auto-dark-mode.nvim",
    opts = {
      update_background = false,
      set_dark_mode = function()
        vim.cmd("colorscheme catppuccin-mocha")
      end,
      set_light_mode = function()
        vim.cmd("colorscheme catppuccin-latte")
      end,
    },
  },

}
