-- Amekoji - Generated by FormalConf
-- Neovim colorscheme configuration for LazyVim

return {
  {
    "bjarneo/aether.nvim",
    priority = 1000,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },

}
