# general
background = '#100f0f'
border_fg = '#282726'
text_fg = '#cecdc3'
dimmed_text_fg = '#575653'
# input
input_text_fg = '#d14d41'
result_count_fg = '#d14d41'
# results
result_name_fg = '#4385be'
result_line_number_fg = '#d0a115'
result_value_fg = '#8c7ec8'
selection_fg = '#879a39'
selection_bg = '#1c1b1a'
match_fg = '#d14d41'
# preview
preview_title_fg = '#da702c'
# modes
channel_mode_fg = '#ce5d97'
remote_control_mode_fg = '#879a39'
send_to_channel_mode_fg = '#3aa9a0'
