return {
  {
    "xiyaowong/transparent.nvim",
    enabled = false,
    opts = {
      -- Do not make the cmp highlight transparent
      -- CmpItemAbbrMatch = { fg = colors.keyword },
      -- CmpItemAbbrMatchFuzzy = { fg = colors.func },
      -- CmpItemKindText = { fg = colors.string },
      -- CmpItemKindMethod = { fg = colors.keyword },
      -- CmpItemKindFunction = { fg = colors.func },
      -- CmpItemKindConstructor = { fg = colors.keyword },
      -- CmpItemKindField = { fg = colors.entity },
      -- CmpItemKindVariable = { fg = colors.tag },
      -- CmpItemKindClass = { fg = colors.entity },
      -- CmpItemKindInterface = { fg = colors.entity },
      -- CmpItemKindModule = { fg = colors.keyword },
      -- CmpItemKindProperty = { fg = colors.keyword },
      -- CmpItemKindUnit = { fg = colors.constant },
      -- CmpItemKindValue = { fg = colors.constant },
      -- CmpItemKindEnum = { fg = colors.entity },
      -- CmpItemKindKeyword = { fg = colors.keyword },
      -- CmpItemKindSnippet = { fg = colors.regexp },
      -- CmpItemKindColor = { fg = colors.special },
      -- CmpItemKindFile = { fg = colors.special },
      -- CmpItemKindReference = { fg = colors.special },
      -- CmpItemKindFolder = { fg = colors.special },
      -- CmpItemKindEnumMember = { fg = colors.constant },
      -- CmpItemKindConstant = { fg = colors.constant },
      -- CmpItemKindStruct = { fg = colors.entity },
      -- CmpItemKindEvent = { fg = colors.tag },
      -- CmpItemKindOperator = { fg = colors.operator },
      -- CmpItemKindTypeParameter = { fg = colors.tag },
      -- CmpItemMenu = { fg = colors.comment },
      exclude_groups = { "CmpItemAbbrMatch", "CmpItemAbbrMatchFuzzy", "CmpItemKindText", "CmpItemKindMethod", "CmpItemKindFunction", "CmpItemKindConstructor", "CmpItemKindField", "CmpItemKindVariable", "CmpItemKindClass", "CmpItemKindInterface", "CmpItemKindModule", "CmpItemKindProperty", "CmpItemKindUnit", "CmpItemKindValue", "CmpItemKindEnum", "CmpItemKindKeyword", "CmpItemKindSnippet", "CmpItemKindColor", "CmpItemKindFile", "CmpItemKindReference", "CmpItemKindFolder", "CmpItemKindEnumMember", "CmpItemKindConstant", "CmpItemKindStruct", "CmpItemKindEvent", "CmpItemKindOperator", "CmpItemKindTypeParameter", "CmpItemMenu" },
    },
  }
}
