#!/bin/bash
# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
export FONT="GeistMono Nerd Font"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=54 \
	blur_radius=30 \
	position=top \
	sticky=off \
	padding_left=4 \
	padding_right=4 \
	color=$TRANSPARENT

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="$FONT:Semibold:15.0" \
	icon.color=$WHITE \
	label.font="$FONT:Semibold:15.0" \
	label.color=$WHITE \
	background.color=$ITEM_BG_COLOR \
	background.corner_radius=5 \
	background.height=35 \
	background.border_width=2 \
	background.border_color=0x55111314 \
	padding_left=5 \
	padding_right=5 \
	label.padding_left=4 \
	label.padding_right=10 \
	blur_radius=30 \
	icon.padding_left=10 \
	icon.padding_right=4
# background.shadow.color=0x25000000 # background.shadow.drawing=on \

# -- Left Side Items --
# source $ITEM_DIR/menu.sh
# source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh
# source $ITEM_DIR/svim.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# --- Right Side Items ---

# source $ITEM_DIR/volume.sh
source $ITEM_DIR/clock.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/wifi.sh
# source $ITEM_DIR/github.sh
source $ITEM_DIR/bracket.sh
# source $ITEM_DIR/disk.sh
# source $ITEM_DIR/cpu.sh
source $ITEM_DIR/weather.sh
# source $ITEM_DIR/notion.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
